apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevali
rules:
  #
  # Required by template functions:
  # getRandomNodeIP, getNodeIPWithIndex
  #
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]

  #
  # Required by nodeService
  #
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "create", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
