apiVersion: v1
kind: Service
metadata:
  name: kubevali
spec:
  type: ClusterIP
  ports:
    - name: rpc
      port: 9933
      targetPort: rpc

    - name: ws
      port: 9944
      targetPort: ws

    - name: metrics
      port: 9615
      targetPort: metrics
