apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kubevali
spec:
  serviceName: kubevali-headless
  replicas: 1

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi

  template:
    spec:
      serviceAccountName: kubevali
      enableServiceLinks: false

      volumes:
        - name: snapshot
          emptyDir: {}
        - name: kubevali
          emptyDir: {}
        - name: config
          configMap:
            name: kubevali

      initContainers:
        - name: init-snapshot
          image: quay.io/darwinia-network/snapshot-init-container
          volumeMounts:
            - name: data
              mountPath: /data
            - name: snapshot
              mountPath: /snapshot

        - name: init-kubevali
          image: quay.io/darwinia-network/kubevali
          volumeMounts:
            - name: kubevali
              mountPath: /volume
          command:
            - cp
            - /kubevali
            - /volume/kubevali

      containers:
        - name: node
          image: quay.io/darwinia-network/darwinia
          volumeMounts:
            - name: data
              mountPath: /data
            - name: kubevali
              mountPath: /kubevali
            - name: config
              mountPath: /config

          command:
            - /kubevali/kubevali
            - --config=/config/kubevali.yaml
            - --watch-config

          ports:
            - name: rpc
              containerPort: 9933
            - name: ws
              containerPort: 9944
            - name: metrics
              containerPort: 9615
            - name: healthz
              containerPort: 49944

          startupProbe:
            httpGet:
              path: /healthz
              port: healthz
            failureThreshold: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz

          # readinessProbe:
          #   httpGet:
          #     path: /readiness
          #     port: healthz

          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 2Gi

        - name: liveness-probe
          image: quay.io/darwinia-network/node-liveness-probe
          resources:
            requests:
              cpu: 50m
              memory: 20Mi
            limits:
              cpu: 200m
              memory: 50Mi
