apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../deploy/manifests

namespace: default
nameSuffix: -darwinia
commonLabels:
  app: kubevali
  chain: darwinia

images:
  - name: quay.io/darwinia-network/kubevali
    newTag: v0.3.0
  - name: quay.io/darwinia-network/darwinia
    newTag: v0.10.0
  - name: quay.io/darwinia-network/node-liveness-probe
    newTag: v0.5.1

configMapGenerator:
  - name: kubevali
    files:
      - kubevali.yaml
