commonTemplate: |
  {{- define "nodePort" -}}
  {{ add 30333 .Index }}
  {{- end -}}

nodeTemplate:
  command:
    - darwinia

  args:
    name: '[KUBE-VALI] Example {{ printf "%02d" .Index }}'
    port: '{{ template "nodePort" . }}'
