apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../manifests

namespace: default
nameSuffix: -darwinia
commonLabels:
  app: kubevali
  chain: darwinia

images:
  - name: quay.io/darwinia-network/darwinia
    newTag: v0.10.0

configMapGenerator:
  - name: kubevali
    files:
      - kubevali.yaml
